// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader {
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String, dynamic> ar = {
    "signup_button": "انشاء حساب",
    "login_button": "تسجيل الدخول",
    "welcom_message": "اهلا , مرحبا بعودتك",
    "phone": "رقم الهاتف",
    "country_code": "كود الدولة",
    "password": "كلمة المرور",
    "forget_password": "نسيت كلمة المرور ؟",
    "not_have_account": "لست عضوا في مجتمعنا بعد؟",
    "join": "انضم الان",
    "student": "مسترشد",
    "consultant": "مستشار",
    "full_name": "الاسم بالكامل",
    "email": "البريد الالكتروني",
    "create_account": "انشاء حساب",
    "have_account": "لديك حساب",
    "log": "تسجيل الدخول",
    "register_title": "إنشاء حساب والانضمام",
    "reset_passowrd": "إعادة تعيين كلمة المرور",
    "forget_message": "ستتلقى كود تعريفي لإعادة تعيين كلمة المرور الخاصة بك",
    "send_link": "أرسل كود لإعادة تعيين كلمة المرور",
    "plans_prices": "الخطط والأسعار",
    "home_filter_message":
        "اختر الاستشاري الذي تريد التواصل معه باستخدام المرشحات",
    "language": "اللغة",
    "gender": "النوع",
    "home": "الرئيسية",
    "book": "حجز",
    "menue": "القائمة",
    "consultants": "استشاريون",
    "message": "الرسائل",
    "view_profile": "الملف الشخصي",
    "search": "بحث",
    "book_message": "اختر التاريخ والوقت واعرض المعلمين المتاحين",
    "pick_day": "الرجاء اختيار الأيام التي تريدها",
    "time_period": "فترة زمنية",
    "consultation_time": "وقت الاستشارة",
    "chat_title":
        "إذا كنت ترغب في بدء الدردشة مع مدرس ، يرجى الاشتراك في تسامي",
    "see_plans": "انظر الخطط",
    "my_profile": "حسابي",
    "log_out": "الخروج",
    "profile": "الملف الشخصي",
    "name": "الاسم",
    "country": "الدولة",
    "birth_date": "تاريخ الميلاد",
    "verify_password": "اكد كلمة المرور",
    "update": "تحديث",
    "delete_account": "حذف الحساب",
    "subscription": "الاشتراك",
    "address": "العنوان",
    "subscribe_now": "اشترك الان",
    "vedio_recording": "ميزات تسجيل الفيديو قيد التشغيل",
    "course_plan": "خطة الكورس: ليس لديك أي اشتراك حتى الآن.",
    "select_country": "حدد الدولة",
    "zip_code": "الرمز البريدي",
    "profile_message": "يمكنك تخصيص ملفك الشخصي هنا",
    "send_message": "ارسال رسالة",
    "hobbies": "الهوايات",
    "shcool": "التعليم",
    "about": "حول",
    "select_time": "اختر وقتًا متاحًا في تقويم معلمك",
    "not_found_time":
        "لا تستطيع إيجاد الوقت المناسب لك؟ يمكنك طلب الوقت المتاح من المعلم",
    "make_request": "قدم طلبا",
    "reviews": "التعليقات",
    "more": "المزيد",
    "my_favourite": "المستشارين المفضلين لدي",
    "certificate": "الشهادة",
    "our_blog": "مدونتنا",
    "contact_us": "تواصل معنا",
    "about_us": "من نحن",
    "questionare": "استبيان",
    "terms_conditions": "الأحكام والشروط",
    "privacy_policy": "سياسة الخصوصية",
    "favourite_message": "يمكنك مشاهدة المستشارين المفضلين لديك هنا",
    "certificate_massage":
        "احصل على شهادة عندما تكمل 30 ساعة من ممارسة التحدث باللغة التركية",
    "hours_left": "لديك 30 ساعة متبقية للحصول علي الشهاده",
    "download": "تحميل",
    "writting": "المقالات",
    "success_story": "قصص النجاح",
    "write_your_story": "اكتب قصتك",
    "success_story_message": "تعرف علينا من طلابنا",
    "write_blog": "اكتب مدونتك الان",
    "publish_now": "نشر الان",
    "send": "ارسال",
    "next": "التالي",
    "best_seller": "الافضل مبيعا",
    "start": "ابدء",
    "customize_plan": "تخصيص هذه الخطة",
    "online_payment": "الدفع اونلاين ",
    "online_payment_message":
        "يمكنك الدفع مباشرة عبر طرق دفع مختلفة مثل بطاقة الائتمان ، والتأشيرة ، ودفع جوجل ، ودفع آبل ، إلخ",
    "bank_payment": "الدفع بواسطة التحويل البنكي",
    "bank_transfer_message":
        "يمكنك استخدام wise , ويسترن يونيون , التحويل البنكي",
    "paypal": "الدفع بواسطة paypal",
    "paypal_message": "ادفع بسهوله مع paypal",
    "male": "ذكر",
    "female": "انثي"
  };
  static const Map<String, dynamic> en = {
    "signup_button": "Sign up",
    "login_button": "Log in",
    "welcom_message": "Hi , Welcome back",
    "phone": "Phone number",
    "country_code": "conutry code",
    "password": "password",
    "forget_password": "Forget your password ?",
    "not_have_account": "Not amember of our community yet ? ",
    "join": "Join now",
    "student": "Guided",
    "consultant": "Consultant",
    "full_name": "Full name",
    "email": "Email",
    "create_account": "Create Account",
    "have_account": "Have an Account ",
    "log": "Login",
    "register_title": "Create an Account and join",
    "reset_passowrd": "Reset Password",
    "forget_message": "you will get averification code to reset your password",
    "send_link": "send code to reset password",
    "plans_prices": "Plans & prices",
    "home_filter_message":
        "Choose the consultant that you want to study with by using filters",
    "language": "Language",
    "gender": "Gender",
    "home": "Home",
    "book": "Book",
    "menue": "Menue",
    "consultants": "Consultants",
    "message": "Message",
    "view_profile": "profile",
    "search": "Search",
    "book_message": "Choose a date & time and view the available tutors",
    "pick_day": "Please pick the days you desire",
    "time_period": "Time period",
    "consultation_time": "Consultation Time",
    "chat_title":
        "if you want to start chat with a tutor , please Subscribe to Tasame",
    "see_plans": "See plans",
    "my_profile": "My profile",
    "log_out": "Log out",
    "profile": "Profile",
    "name": "Name",
    "country": "Country",
    "birth_date": "Birth Date",
    "verify_password": "Verify Password",
    "update": "Update",
    "delete_account": "Delete Account",
    "subscription": "Subscription",
    "address": "Address",
    "subscribe_now": "Subscribe Now",
    "vedio_recording": "video recording features is on",
    "course_plan": "Course plan : you don't have any subscription yet.",
    "select_country": "Select country",
    "zip_code": "Zip Code",
    "profile_message": "you can customize your profile here",
    "send_message": "Send Message",
    "hobbies": "Hobbies",
    "shcool": "School",
    "about": "About",
    "select_time": "Pick an available time on your tutor's calender",
    "not_found_time":
        "Couldn't find the right time for you ? you can Request available time from the teacher",
    "make_request": "Make Request",
    "reviews": "Reviews",
    "more": "More",
    "my_favourite": "My Favourite Tutors",
    "certificate": "Certificate",
    "our_blog": "Our Blog",
    "contact_us": "Contact us",
    "about_us": "About us",
    "questionare": "Quastionare",
    "terms_conditions": "Terms and Conditions",
    "privacy_policy": "Privacy Policy",
    "favourite_message": "you view your favourite tutors here",
    "certificate_massage":
        "Get a certificate when you complete 30 hours of Turkish speaking practice",
    "hours_left": "you have 30 hours left to qualify for certification",
    "download": "Download",
    "writting": "Writting",
    "success_story": "Success Stories",
    "write_your_story": "write your story",
    "success_story_message": "Learn about us from our students",
    "write_blog": "Write your blog now ",
    "publish_now": "Publish now",
    "send": "Send",
    "next": "Next",
    "best_seller": "Best Seller",
    "start": "Start",
    "customize_plan": "Customize this plan",
    "online_payment": "Online Payment",
    "online_payment_message":
        "you can directly pay via different payment methods like Credit card , visa , Google pay , Apple pay etc",
    "bank_payment": "Payment by bank transfer",
    "bank_transfer_message":
        "you can use Wise , Western Union , Bank transfer (ios)",
    "paypal": "Pay by paypal",
    "paypal_message": "pay easily with paypal",
    "male": "Male",
    "female": "Female"
  };

  static const Map<String, dynamic> tr = {
    "signup_button": "Üye olmak",
    "login_button": "Giriş yapmak",
    "welcom_message": "Merhaba , tekrar hoşgeldiniz",
    "phone": "Telefon numarası",
    "country_code": "ülke kodu",
    "password": "parola",
    "forget_password": "Şifreni mi unuttun ?",
    "not_have_account": "Henüz topluluğumuzun bir üyesi değil misiniz?",
    "join": "Şimdi Katıl",
    "student": "Öğrenci",
    "consultant": "Danışman",
    "full_name": "Ad Soyad",
    "email": "E-posta",
    "create_account": "Hesap oluştur",
    "have_account": "Hesap sahibi ol ",
    "log": "Giriş yapmak",
    "register_title": "Bir Hesap oluşturun ve katılın",
    "reset_passowrd": "Şifreyi yenile",
    "forget_message": "şifrenizi sıfırlamak için bir e-posta alacaksınız",
    "send_link": "şifreyi sıfırlamak için bağlantı gönder",
    "plans_prices": "Planlar ve fiyatlar",
    "home_filter_message":
        "Filtreleri kullanarak çalışmak istediğiniz danışmanı seçin",
    "language": "Dil",
    "gender": "Cinsiyet",
    "home": "Ev",
    "book": "Rezervasyon",
    "menue": "Menü",
    "consultants": "Danışmanlar",
    "message": "İleti",
    "view_profile": "Profili Görüntüle",
    "search": "Aramak",
    "book_message":
        "Bir tarih ve saat seçin ve uygun öğretmenleri görüntüleyin",
    "pick_day": "Lütfen istediğiniz günleri seçin",
    "time_period": "Zaman dilimi",
    "consultation_time": "Danışma Süresi",
    "chat_title":
        "Bir öğretmenle sohbete başlamak istiyorsanız, lütfen Zat'a abone olun.",
    "see_plans": "planlara bakın",
    "my_profile": "Benim profilim",
    "log_out": "Çıkış Yap",
    "profile": "Profil",
    "name": "İsim",
    "country": "Ülke",
    "birth_date": "Doğum günü",
    "verify_password": "Parolayı Doğrula",
    "update": "Güncelleme",
    "delete_account": "Hesabı sil",
    "subscription": "abonelik",
    "address": "Adres",
    "subscribe_now": "Şimdi Abone Ol",
    "vedio_recording": "video kayıt özellikleri açık",
    "course_plan": "Kurs planı : Henüz herhangi bir aboneliğiniz yok.",
    "select_country": "ülke seç",
    "zip_code": "Posta kodu",
    "profile_message": "profilinizi burada özelleştirebilirsiniz",
    "send_message": "Mesaj gönder",
    "hobbies": "Hobiler",
    "shcool": "Okul",
    "about": "Hakkında",
    "select_time": "Öğretmeninizin takviminden uygun bir zaman seçin",
    "not_found_time":
        "Sizin için doğru zamanı bulamadınız mı? öğretmenden müsait zamanı talep edebilirsiniz",
    "make_request": "İstek Yap",
    "reviews": "Yorumlar",
    "more": "Daha",
    "my_favourite": "Favori Öğretmenlerim",
    "certificate": "sertifika",
    "our_blog": "Blogumuz",
    "contact_us": "Bize Ulaşın",
    "about_us": "Hakkımızda",
    "questionare": "anket",
    "terms_conditions": "Şartlar ve koşullar",
    "privacy_policy": "Gizlilik Politikası",
    "favourite_message": "en sevdiğin öğretmenleri burada görebilirsin",
    "certificate_massage":
        "30 saatlik Türkçe konuşma pratiğini tamamladığınızda sertifika alın",
    "hours_left": "sertifika almaya hak kazanmak için 30 saatiniz kaldı",
    "download": "İndirmek",
    "writting": "Yazma",
    "success_story": "Başarı Öyküleri",
    "write_your_story": "hikayeni yaz",
    "success_story_message": "Öğrencilerimizden bizi öğrenin",
    "write_blog": "Blogunuzu şimdi yazın",
    "publish_now": "şimdi yayınla",
    "send": "Göndermek",
    "next": "Sonraki",
    "best_seller": "En çok satan kitap",
    "start": "Başlama",
    "customize_plan": "Bu planı özelleştirin",
    "online_payment": "Online ödeme",
    "online_payment_message":
        "Kredi kartı, visa, Google pay, Apple pay vb. farklı ödeme yöntemleriyle doğrudan ödeme yapabilirsiniz.",
    "bank_payment": "Banka havalesi ile ödeme",
    "bank_transfer_message":
        "Wise , Western Union , Banka havalesi (ios) kullanabilirsiniz",
    "paypal": "Paypal ile öde",
    "paypal_message": "paypal ile kolayca öde",
    "male": "Erkek",
    "female": "Dişi"
  };

  static const Map<String, Map<String, dynamic>> mapLocales = {
    "en": en,
    "ar": ar,
    "tr": tr,
  };
}
